### ISSUE TITLE
Support for DGL & DGL-KG?

### ISSUE THREAD

**Issue by marvin-hansen** [vaticle/kglib#157]
Have you considered DGL as underlying ML engine?

Imho, it's way easier to convert a typeDB query result into a networkX graph which than can be processed by the many state of the art algorithms in DGL instead of reinventing the wheel. This would substantially boost the usefulness of this project and actually give people a strong reason to build on typeDB in the first place. 

https://www.dgl.ai

 https://github.com/awslabs/dgl-ke 

Any thoughts on this?

**Comment by jmsfltchr** [comment]
Totally agree with the above, this project started before the rapid development of the graph learning field and should move towards becoming a tooling library for interfacing with external graph ML projects.

**Comment by marvin-hansen** [comment]
James,

Take a look at Pilosa

https://github.com/pilosa

Any hypergraph can be represented as a NxM matrix and Pilosa does just that
so that might be an option if performance and latency at scale matters and
you can afford a bit of engineering work.

Arango already comes with a ready to use graph deep learning solution for
it's graph. It's marvelous and immediately production ready although no
type system and no rule based reasoning.

If you aren't bound to TypeDB, Arango is the way to go. If you are invested
in TypeDB, well, good luck with patching ML together as your are
essentially all on your own.

**Comment by jmsfltchr** [comment]
Hadn't heard of Pilosa, does look interesting. We moved away from solutions that required the whole knowledge graph to be ingested due to scalability concerns. We thought it better to take a subgraph sampling approach for that reason. Their indexing approach sounds promising though.

As an employee at Vaticle and author of this repo I'll be staying with TypeDB! :)

**Comment by marvin-hansen** [comment]
James,

I concur with the scalability concerns.

 I'm gravely concerned about the relatively lax safety procedures currently
in place, the problematic absence of full master replication, and something
must change with respect to operational issues at scale.

That being said, if you are in a position, please raise the idea to move
away from a key value store, and instead consider a native storage format.
There is a good blog post pointing out the countless problems im sure your
engineering team has already figured out the hard way.

https://www.tigergraph.com/blog/building-a-graph-database-on-a-key-value-store/


As mentioned before, any hypergraph can be expressed as a matrix so moving
to a distributed feature store, which really is a gigantic matrix on
steroids, would solve a lot of the current problems, scale horizontally to
Petabytes with relative ease, and almost certainly reduce CPU load by a
magnitude or more.

TypeDB definitely needs a graph native storage format to move forward.
